import type { EventItem, Faq, SiteData } from "~/types";

const social = {
  instagram: "https://instagram.com/daqtad",
  facebook: "https://fb.com/daqtad",
};

const requests = {
  endpoint: "https://formspree.io/f/xjybleya",
};

const events: EventItem[] = [
  {
    slug: "popup",
    status: "upcoming",
    title: "Spin-Off (Pop-Up) — Bopsim Korean Festival",
    name: "Spin-Off (Pop-Up)",
    subtitle: "Bopsim Korean Festival",
    page: "/events/popup",
    startsAt: "2026-09-11T16:00:00-06:00",
    dateLabel: "Fri, Sep 11 2026",
    timeLabel: "4:00–9:00 PM",
    venue: "Bopsim Korean Festival, University of Utah, Salt Lake City, UT",
    venueShort: "Bopsim Korean Festival, U of U",
    badge: "Upcoming · requests open",
    cta: "Countdown + song requests →",
    poster: "/assets/images/events/popup-poster.jpg",
    posterAlt: "Spin-Off (Pop-Up) at Bopsim Korean Festival event poster",
    cover: "/assets/images/events/popup-cover.jpg",
    requestsOpen: true,
    video: "",
    photos: [],
    rounds: [],
  },
  {
    slug: "rpd-ut2",
    status: "past",
    title: "#RPD_UT2 — Season's Greetings",
    name: "#RPD_UT2",
    subtitle: "Season's Greetings",
    page: "",
    startsAt: "2026-01-10T18:00:00-07:00",
    dateLabel: "Sat, Jan 10 2026",
    monthLabel: "Jan 2026",
    venue: "",
    venueShort: "",
    cta: "Setlist →",
    poster: "/assets/images/events/rpd-ut2-poster.jpg",
    posterAlt: "#RPD_UT2 Season's Greetings event poster",
    cover: "/assets/images/events/rpd-ut2-cover.jpg",
    video: "",
    photos: [],
    rounds: [],
  },
  {
    slug: "rpd-ut1",
    status: "past",
    title: "#RPD_UT1 — Back To School Fall 2025",
    name: "#RPD_UT1",
    subtitle: "Back To School Fall 2025",
    page: "",
    startsAt: "2025-08-16T18:00:00-06:00",
    dateLabel: "Sat, Aug 16 2025",
    monthLabel: "Aug 2025",
    venue: "",
    venueShort: "",
    cta: "Setlist →",
    poster: "/assets/images/events/rpd-ut1-poster.jpg",
    posterAlt: "#RPD_UT1 Back To School Fall 2025 event poster",
    cover: "/assets/images/events/rpd-ut1-cover.jpg",
    video: "",
    photos: [],
    rounds: [],
  },
  {
    slug: "rdd-6",
    status: "past",
    title: "#RDD6 — DA'COMEBACK",
    name: "#RDD6",
    subtitle: "DA'COMEBACK",
    page: "",
    startsAt: "2022-07-24T18:00:00+07:00",
    dateLabel: "Sun, Jul 24 2022",
    monthLabel: "Jul 2022",
    venue: "",
    venueShort: "",
    cta: "Setlist →",
    poster: "/assets/images/events/rdd-6-poster.jpg",
    posterAlt: "#RDD6 DA'COMEBACK event poster",
    cover: "/assets/images/events/rdd-6-cover.jpg",
    video: "",
    photos: [],
    rounds: [],
  },
  {
    slug: "antivirus",
    status: "past",
    title: "Spin-Off — ANTIVIRUS",
    name: "Spin-Off",
    subtitle: "ANTIVIRUS",
    page: "",
    startsAt: "2020-08-30T18:00:00+07:00",
    dateLabel: "Sun, Aug 30 2020",
    monthLabel: "Aug 2020",
    venue: "",
    venueShort: "",
    cta: "Setlist →",
    poster: "/assets/images/events/antivirus-poster.jpg",
    posterAlt: "Spin-Off ANTIVIRUS event poster",
    cover: "/assets/images/events/antivirus-cover.jpg",
    video: "",
    photos: [],
    rounds: [],
  },
  {
    slug: "rdd-5",
    status: "past",
    title: "#RDD5 — ONE NEW YEAR. ONE ANNIVERSARY.",
    name: "#RDD5",
    subtitle: "ONE NEW YEAR. ONE ANNIVERSARY.",
    page: "",
    startsAt: "2020-01-29T18:00:00+07:00",
    dateLabel: "Wed, Jan 29 2020",
    monthLabel: "Jan 2020",
    venue: "",
    venueShort: "",
    cta: "Setlist →",
    poster: "/assets/images/events/rdd-5-poster.jpg",
    posterAlt: "#RDD5 event poster",
    cover: "/assets/images/events/rdd-5-cover.jpg",
    video: "",
    photos: [],
    rounds: [],
  },
  {
    slug: "rdd-4",
    status: "past",
    title: "#RDD4 — Look Back 2019",
    name: "#RDD4",
    subtitle: "Look Back 2019",
    page: "",
    startsAt: "2019-12-29T18:00:00+07:00",
    dateLabel: "Sun, Dec 29 2019",
    monthLabel: "Dec 2019",
    venue: "",
    venueShort: "",
    cta: "Setlist →",
    poster: "/assets/images/events/rdd-4-poster.jpg",
    posterAlt: "#RDD4 Look Back 2019 event poster",
    cover: "/assets/images/events/rdd-4-cover.jpg",
    video: "",
    photos: [],
    rounds: [],
  },
  {
    slug: "rdd-3",
    status: "past",
    title: "#RDD3 — Back To School",
    name: "#RDD3",
    subtitle: "Back To School",
    page: "",
    startsAt: "2019-08-02T18:00:00+07:00",
    dateLabel: "Fri, Aug 2 2019",
    monthLabel: "Aug 2019",
    venue: "",
    venueShort: "",
    cta: "Setlist →",
    poster: "/assets/images/events/rdd-3-poster.jpg",
    posterAlt: "#RDD3 Back To School event poster",
    cover: "/assets/images/events/rdd-3-cover.jpg",
    video: "",
    photos: [],
    rounds: [],
  },
  {
    slug: "rdd-2",
    status: "past",
    title: "#RDD2 — Offline Kpop Fan",
    name: "#RDD2",
    subtitle: "Offline Kpop Fan",
    page: "",
    startsAt: "2019-07-06T18:00:00+07:00",
    dateLabel: "Sat, Jul 6 2019",
    monthLabel: "Jul 2019",
    venue: "",
    venueShort: "",
    cta: "Setlist →",
    poster: "/assets/images/events/rdd-2-poster.jpg",
    posterAlt: "#RDD2 Offline Kpop Fan event poster",
    cover: "/assets/images/events/rdd-2-cover.jpg",
    video: "",
    photos: [],
    rounds: [],
  },
  {
    slug: "rdd-1",
    status: "past",
    title: "#RDD1 — Random Dance The Debut in Ben Tre, VN",
    name: "#RDD1",
    subtitle: "Random Dance The Debut in Ben Tre, VN",
    page: "",
    startsAt: "2019-01-30T18:00:00+07:00",
    dateLabel: "Wed, Jan 30 2019",
    monthLabel: "Jan 2019",
    venue: "Bến Tre, Vietnam",
    venueShort: "Bến Tre, VN",
    cta: "Setlist →",
    poster: "/assets/images/events/rdd-1-poster.jpg",
    posterAlt: "#RDD1 debut event poster",
    cover: "/assets/images/events/rdd-1-cover.jpg",
    video: "",
    photos: [],
    rounds: [],
  },
];

const faqs: Faq[] = [
  {
    q: "What is a random play dance (RPD)?",
    a: "A playlist of K-pop songs plays in short segments in random order. When a song you know comes on, run to the center and dance the choreography. When it ends, run back. Chaos, in the best way.",
  },
  {
    q: "Do I need to know the full choreography?",
    a: "Nope! Most people only know the chorus — that is totally fine. Dance what you know, vibe for the rest.",
  },
  {
    q: "Is it free? Do I need to register?",
    a: "Always free, no registration. Just show up. Follow @daqtad on Instagram so you know when and where.",
  },
  {
    q: "How do song requests work?",
    a: "Before each event we open requests on the event page. The most-requested songs make the playlist. One request per song, but you can request as many songs as you like.",
  },
  {
    q: "Can I get the photos from an event?",
    a: "Yes! Photos live on that event's page and in the gallery. Some events also have their own Google Drive album — free to download and post (tag us 💜).",
  },
];

export function sampleSite(): SiteData {
  return {
    source: "sample",
    social,
    requests,
    events,
    faqs,
  };
}
