-- ===========================================================================
-- DA'QTAD — starter content, generated from the site's original data file.
-- Run this ONCE, right after schema.sql. Re-running resets every setlist,
-- so once you start editing in the admin, do not run it again.
-- ===========================================================================

-- 135 songs in the library
insert into public.songs (title, artist) values
  ('Whiplash', 'aespa'),
  ('APT.', 'ROSÉ & Bruno Mars'),
  ('How Sweet', 'NewJeans'),
  ('Magnetic', 'ILLIT'),
  ('Fate', '(G)I-DLE'),
  ('SPOT!', 'ZICO & JENNIE'),
  ('Sticky', 'KISS OF LIFE'),
  ('Chk Chk Boom', 'Stray Kids'),
  ('Armageddon', 'aespa'),
  ('Igloo', 'KISS OF LIFE'),
  ('Mantra', 'JENNIE'),
  ('POWER', 'G-Dragon'),
  ('Supernova', 'aespa'),
  ('EASY', 'LE SSERAFIM'),
  ('Deja Vu', 'TXT'),
  ('Impossible', 'RIIZE'),
  ('SHEESH', 'BABYMONSTER'),
  ('Super Shy', 'NewJeans'),
  ('S-Class', 'Stray Kids'),
  ('I AM', 'IVE'),
  ('Queencard', '(G)I-DLE'),
  ('Spicy', 'aespa'),
  ('UNFORGIVEN', 'LE SSERAFIM'),
  ('Ditto', 'NewJeans'),
  ('Teddy Bear', 'STAYC'),
  ('Drama', 'aespa'),
  ('Perfect Night', 'LE SSERAFIM'),
  ('Standing Next to You', 'Jung Kook'),
  ('Get A Guitar', 'RIIZE'),
  ('You & Me', 'JENNIE'),
  ('Love Me Again', 'V'),
  ('HOT', 'LE SSERAFIM'),
  ('Kill This Love', 'BLACKPINK'),
  ('How You Like That', 'BLACKPINK'),
  ('DDU-DU DDU-DU', 'BLACKPINK'),
  ('Pink Venom', 'BLACKPINK'),
  ('Shut Down', 'BLACKPINK'),
  ('Lovesick Girls', 'BLACKPINK'),
  ('BOOMBAYAH', 'BLACKPINK'),
  ('As If It’s Your Last', 'BLACKPINK'),
  ('Dynamite', 'BTS'),
  ('Butter', 'BTS'),
  ('Boy With Luv', 'BTS'),
  ('IDOL', 'BTS'),
  ('FAKE LOVE', 'BTS'),
  ('DNA', 'BTS'),
  ('Blood Sweat & Tears', 'BTS'),
  ('MIC Drop', 'BTS'),
  ('Permission to Dance', 'BTS'),
  ('FANCY', 'TWICE'),
  ('TT', 'TWICE'),
  ('LIKEY', 'TWICE'),
  ('What is Love?', 'TWICE'),
  ('Feel Special', 'TWICE'),
  ('MORE & MORE', 'TWICE'),
  ('I CAN’T STOP ME', 'TWICE'),
  ('The Feels', 'TWICE'),
  ('SET ME FREE', 'TWICE'),
  ('Cheer Up', 'TWICE'),
  ('Next Level', 'aespa'),
  ('Savage', 'aespa'),
  ('Black Mamba', 'aespa'),
  ('Girls', 'aespa'),
  ('Dun Dun Dance', 'OH MY GIRL'),
  ('Nonstop', 'OH MY GIRL'),
  ('Secret Garden', 'OH MY GIRL'),
  ('LOVE DIVE', 'IVE'),
  ('After LIKE', 'IVE'),
  ('ELEVEN', 'IVE'),
  ('Kitsch', 'IVE'),
  ('Baddie', 'IVE'),
  ('Either Way', 'IVE'),
  ('Attention', 'NewJeans'),
  ('Hype Boy', 'NewJeans'),
  ('OMG', 'NewJeans'),
  ('ETA', 'NewJeans'),
  ('Cookie', 'NewJeans'),
  ('Bubble Gum', 'NewJeans'),
  ('ANTIFRAGILE', 'LE SSERAFIM'),
  ('FEARLESS', 'LE SSERAFIM'),
  ('Smart', 'LE SSERAFIM'),
  ('CRAZY', 'LE SSERAFIM'),
  ('TOMBOY', '(G)I-DLE'),
  ('Nxde', '(G)I-DLE'),
  ('LATATA', '(G)I-DLE'),
  ('Oh my god', '(G)I-DLE'),
  ('Super Lady', '(G)I-DLE'),
  ('Klaxon', '(G)I-DLE'),
  ('God’s Menu', 'Stray Kids'),
  ('Back Door', 'Stray Kids'),
  ('MANIAC', 'Stray Kids'),
  ('CASE 143', 'Stray Kids'),
  ('LALALALA', 'Stray Kids'),
  ('Thunderous', 'Stray Kids'),
  ('Growl', 'EXO'),
  ('Love Shot', 'EXO'),
  ('Monster', 'EXO'),
  ('Ko Ko Bop', 'EXO'),
  ('FANTASTIC BABY', 'BIGBANG'),
  ('BANG BANG BANG', 'BIGBANG'),
  ('Gangnam Style', 'PSY'),
  ('That That', 'PSY'),
  ('HIP', 'MAMAMOO'),
  ('Dingga', 'MAMAMOO'),
  ('Egotistic', 'MAMAMOO'),
  ('Psycho', 'Red Velvet'),
  ('Red Flavor', 'Red Velvet'),
  ('Bad Boy', 'Red Velvet'),
  ('Queendom', 'Red Velvet'),
  ('Feel My Rhythm', 'Red Velvet'),
  ('Peek-A-Boo', 'Red Velvet'),
  ('ASAP', 'STAYC'),
  ('RUN2U', 'STAYC'),
  ('Stereotype', 'STAYC'),
  ('WANNABE', 'ITZY'),
  ('DALLA DALLA', 'ITZY'),
  ('Not Shy', 'ITZY'),
  ('LOCO', 'ITZY'),
  ('SNEAKERS', 'ITZY'),
  ('Cheshire', 'ITZY'),
  ('Born to Be', 'ITZY'),
  ('Bouncy', 'ATEEZ'),
  ('Wonderland', 'ATEEZ'),
  ('Say My Name', 'ATEEZ'),
  ('Guerrilla', 'ATEEZ'),
  ('Cherry Bomb', 'NCT 127'),
  ('Kick It', 'NCT 127'),
  ('Sticker', 'NCT 127'),
  ('Hot Sauce', 'NCT DREAM'),
  ('Ridin’', 'NCT DREAM'),
  ('Smoothie', 'NCT DREAM'),
  ('Gashina', 'SUNMI'),
  ('TAIL', 'SUNMI'),
  ('Cupid', 'FIFTY FIFTY'),
  ('Rollin’', 'Brave Girls')
on conflict do nothing;

insert into public.events (slug, name, subtitle, status, starts_at, ends_at,
  venue, venue_short, badge, cta, stats, poster_url, cover_url, video,
  requests_open, page, position) values (
  'vol-8', 'RPD Vol. 8', 'Neon Nights', 'upcoming', '2026-10-17T18:00:00-06:00', '2026-10-17T21:00:00-06:00', 'Liberty Park (east pavilion), Salt Lake City, UT', 'Liberty Park, SLC', 'Upcoming · requests open', 'Countdown + song requests →', '', 'assets/images/events/vol-8-poster.jpg', 'assets/images/events/vol-8-cover.jpg', '', true, 'event-vol-8.html', 80
) on conflict (slug) do nothing;

insert into public.events (slug, name, subtitle, status, starts_at, ends_at,
  venue, venue_short, badge, cta, stats, poster_url, cover_url, video,
  requests_open, page, position) values (
  'vol-7', 'RPD Vol. 7', 'Summer Splash', 'past', '2026-07-18T18:00:00-06:00', null, 'Sugar House Park, Salt Lake City, UT', 'Sugar House Park, SLC', '', 'Photos · video · setlist →', '~60 dancers · 3 hours · 3 rounds · 240 songs', 'assets/images/events/vol-7-poster.jpg', 'assets/images/events/vol-7-cover.jpg', '', false, 'event-vol-7.html', 70
) on conflict (slug) do nothing;

insert into public.events (slug, name, subtitle, status, starts_at, ends_at,
  venue, venue_short, badge, cta, stats, poster_url, cover_url, video,
  requests_open, page, position) values (
  'vol-6', 'RPD Vol. 6', 'Bloom', 'past', '2026-04-11T18:00:00-06:00', null, 'Liberty Park, Salt Lake City, UT', 'Liberty Park, SLC', '', 'Photos · video · setlist →', '', 'assets/images/events/vol-6-poster.jpg', 'assets/images/events/vol-6-cover.jpg', '', false, '', 60
) on conflict (slug) do nothing;

insert into public.events (slug, name, subtitle, status, starts_at, ends_at,
  venue, venue_short, badge, cta, stats, poster_url, cover_url, video,
  requests_open, page, position) values (
  'vol-5', 'RPD Vol. 5', 'Year-End Party', 'past', '2025-12-20T18:00:00-07:00', null, 'Indoor studio, Salt Lake City, UT', 'Indoor studio, SLC', '', 'Photos · video · setlist →', '', 'assets/images/events/vol-5-poster.jpg', 'assets/images/events/vol-5-cover.jpg', '', false, '', 50
) on conflict (slug) do nothing;

insert into public.events (slug, name, subtitle, status, starts_at, ends_at,
  venue, venue_short, badge, cta, stats, poster_url, cover_url, video,
  requests_open, page, position) values (
  'vol-4', 'RPD Vol. 4', 'Homecoming (Bến Tre)', 'past', '2025-09-06T18:00:00+07:00', null, 'Bến Tre riverside, Vietnam ✈ farewell RPD', 'Bến Tre riverside, VN', '', 'Photos · video · setlist →', '', 'assets/images/events/vol-4-poster.jpg', 'assets/images/events/vol-4-cover.jpg', '', false, '', 40
) on conflict (slug) do nothing;

-- RPD Vol. 7 — 3 rounds
delete from public.rounds r using public.events e
  where r.event_id = e.id and e.slug = 'vol-7';

insert into public.rounds (event_id, label, position)
select id, 'Round 1 · 6:00 PM', 0 from public.events where slug = 'vol-7';

insert into public.round_songs (round_id, song_id, position)
select r.id, s.id, v.pos
from (values
  ('Whiplash'::text, 'aespa'::text, 0),
  ('APT.', 'ROSÉ & Bruno Mars', 1),
  ('How Sweet', 'NewJeans', 2),
  ('Magnetic', 'ILLIT', 3),
  ('Fate', '(G)I-DLE', 4),
  ('SPOT!', 'ZICO & JENNIE', 5),
  ('Sticky', 'KISS OF LIFE', 6),
  ('Chk Chk Boom', 'Stray Kids', 7),
  ('Armageddon', 'aespa', 8),
  ('Igloo', 'KISS OF LIFE', 9),
  ('Mantra', 'JENNIE', 10),
  ('POWER', 'G-Dragon', 11),
  ('Supernova', 'aespa', 12),
  ('EASY', 'LE SSERAFIM', 13),
  ('Deja Vu', 'TXT', 14),
  ('Impossible', 'RIIZE', 15),
  ('SHEESH', 'BABYMONSTER', 16),
  ('Super Shy', 'NewJeans', 17),
  ('S-Class', 'Stray Kids', 18),
  ('I AM', 'IVE', 19),
  ('Queencard', '(G)I-DLE', 20),
  ('Spicy', 'aespa', 21),
  ('UNFORGIVEN', 'LE SSERAFIM', 22),
  ('Ditto', 'NewJeans', 23),
  ('Teddy Bear', 'STAYC', 24),
  ('Drama', 'aespa', 25),
  ('Perfect Night', 'LE SSERAFIM', 26),
  ('Standing Next to You', 'Jung Kook', 27),
  ('Get A Guitar', 'RIIZE', 28),
  ('You & Me', 'JENNIE', 29),
  ('Love Me Again', 'V', 30),
  ('HOT', 'LE SSERAFIM', 31),
  ('Kill This Love', 'BLACKPINK', 32),
  ('How You Like That', 'BLACKPINK', 33),
  ('DDU-DU DDU-DU', 'BLACKPINK', 34),
  ('Pink Venom', 'BLACKPINK', 35),
  ('Shut Down', 'BLACKPINK', 36),
  ('Lovesick Girls', 'BLACKPINK', 37),
  ('BOOMBAYAH', 'BLACKPINK', 38),
  ('As If It’s Your Last', 'BLACKPINK', 39),
  ('Dynamite', 'BTS', 40),
  ('Butter', 'BTS', 41),
  ('Boy With Luv', 'BTS', 42),
  ('IDOL', 'BTS', 43),
  ('FAKE LOVE', 'BTS', 44),
  ('DNA', 'BTS', 45),
  ('Blood Sweat & Tears', 'BTS', 46),
  ('MIC Drop', 'BTS', 47),
  ('Permission to Dance', 'BTS', 48),
  ('FANCY', 'TWICE', 49),
  ('TT', 'TWICE', 50),
  ('LIKEY', 'TWICE', 51),
  ('What is Love?', 'TWICE', 52),
  ('Feel Special', 'TWICE', 53),
  ('MORE & MORE', 'TWICE', 54),
  ('I CAN’T STOP ME', 'TWICE', 55),
  ('The Feels', 'TWICE', 56),
  ('SET ME FREE', 'TWICE', 57),
  ('Cheer Up', 'TWICE', 58),
  ('Next Level', 'aespa', 59),
  ('Savage', 'aespa', 60),
  ('Black Mamba', 'aespa', 61),
  ('Girls', 'aespa', 62),
  ('Dun Dun Dance', 'OH MY GIRL', 63),
  ('Nonstop', 'OH MY GIRL', 64),
  ('Secret Garden', 'OH MY GIRL', 65),
  ('LOVE DIVE', 'IVE', 66),
  ('After LIKE', 'IVE', 67),
  ('ELEVEN', 'IVE', 68),
  ('Kitsch', 'IVE', 69),
  ('Baddie', 'IVE', 70),
  ('Either Way', 'IVE', 71),
  ('Attention', 'NewJeans', 72),
  ('Hype Boy', 'NewJeans', 73),
  ('OMG', 'NewJeans', 74),
  ('ETA', 'NewJeans', 75),
  ('Cookie', 'NewJeans', 76),
  ('Bubble Gum', 'NewJeans', 77),
  ('ANTIFRAGILE', 'LE SSERAFIM', 78),
  ('FEARLESS', 'LE SSERAFIM', 79),
  ('Smart', 'LE SSERAFIM', 80),
  ('CRAZY', 'LE SSERAFIM', 81),
  ('TOMBOY', '(G)I-DLE', 82),
  ('Nxde', '(G)I-DLE', 83),
  ('LATATA', '(G)I-DLE', 84),
  ('Oh my god', '(G)I-DLE', 85),
  ('Super Lady', '(G)I-DLE', 86),
  ('Klaxon', '(G)I-DLE', 87),
  ('God’s Menu', 'Stray Kids', 88),
  ('Back Door', 'Stray Kids', 89),
  ('MANIAC', 'Stray Kids', 90),
  ('CASE 143', 'Stray Kids', 91),
  ('LALALALA', 'Stray Kids', 92),
  ('Thunderous', 'Stray Kids', 93),
  ('Growl', 'EXO', 94),
  ('Love Shot', 'EXO', 95),
  ('Monster', 'EXO', 96),
  ('Ko Ko Bop', 'EXO', 97),
  ('FANTASTIC BABY', 'BIGBANG', 98),
  ('BANG BANG BANG', 'BIGBANG', 99)
) as v(title, artist, pos)
join public.songs s
  on lower(s.title) = lower(v.title) and lower(s.artist) = lower(v.artist)
join public.rounds r on r.label = 'Round 1 · 6:00 PM'
join public.events e on e.id = r.event_id and e.slug = 'vol-7';

insert into public.rounds (event_id, label, position)
select id, 'Round 2 · 7:30 PM', 1 from public.events where slug = 'vol-7';

insert into public.round_songs (round_id, song_id, position)
select r.id, s.id, v.pos
from (values
  ('Lovesick Girls'::text, 'BLACKPINK'::text, 0),
  ('BOOMBAYAH', 'BLACKPINK', 1),
  ('As If It’s Your Last', 'BLACKPINK', 2),
  ('Dynamite', 'BTS', 3),
  ('Butter', 'BTS', 4),
  ('Boy With Luv', 'BTS', 5),
  ('IDOL', 'BTS', 6),
  ('FAKE LOVE', 'BTS', 7),
  ('DNA', 'BTS', 8),
  ('Blood Sweat & Tears', 'BTS', 9),
  ('MIC Drop', 'BTS', 10),
  ('Permission to Dance', 'BTS', 11),
  ('FANCY', 'TWICE', 12),
  ('TT', 'TWICE', 13),
  ('LIKEY', 'TWICE', 14),
  ('What is Love?', 'TWICE', 15),
  ('Feel Special', 'TWICE', 16),
  ('MORE & MORE', 'TWICE', 17),
  ('I CAN’T STOP ME', 'TWICE', 18),
  ('The Feels', 'TWICE', 19),
  ('SET ME FREE', 'TWICE', 20),
  ('Cheer Up', 'TWICE', 21),
  ('Next Level', 'aespa', 22),
  ('Savage', 'aespa', 23),
  ('Black Mamba', 'aespa', 24),
  ('Girls', 'aespa', 25),
  ('Dun Dun Dance', 'OH MY GIRL', 26),
  ('Nonstop', 'OH MY GIRL', 27),
  ('Secret Garden', 'OH MY GIRL', 28),
  ('LOVE DIVE', 'IVE', 29),
  ('After LIKE', 'IVE', 30),
  ('ELEVEN', 'IVE', 31),
  ('Kitsch', 'IVE', 32),
  ('Baddie', 'IVE', 33),
  ('Either Way', 'IVE', 34),
  ('Attention', 'NewJeans', 35),
  ('Hype Boy', 'NewJeans', 36),
  ('OMG', 'NewJeans', 37),
  ('ETA', 'NewJeans', 38),
  ('Cookie', 'NewJeans', 39),
  ('Bubble Gum', 'NewJeans', 40),
  ('ANTIFRAGILE', 'LE SSERAFIM', 41),
  ('FEARLESS', 'LE SSERAFIM', 42),
  ('Smart', 'LE SSERAFIM', 43),
  ('CRAZY', 'LE SSERAFIM', 44),
  ('TOMBOY', '(G)I-DLE', 45),
  ('Nxde', '(G)I-DLE', 46),
  ('LATATA', '(G)I-DLE', 47),
  ('Oh my god', '(G)I-DLE', 48),
  ('Super Lady', '(G)I-DLE', 49),
  ('Klaxon', '(G)I-DLE', 50),
  ('God’s Menu', 'Stray Kids', 51),
  ('Back Door', 'Stray Kids', 52),
  ('MANIAC', 'Stray Kids', 53),
  ('CASE 143', 'Stray Kids', 54),
  ('LALALALA', 'Stray Kids', 55),
  ('Thunderous', 'Stray Kids', 56),
  ('Growl', 'EXO', 57),
  ('Love Shot', 'EXO', 58),
  ('Monster', 'EXO', 59),
  ('Ko Ko Bop', 'EXO', 60),
  ('FANTASTIC BABY', 'BIGBANG', 61),
  ('BANG BANG BANG', 'BIGBANG', 62),
  ('Gangnam Style', 'PSY', 63),
  ('That That', 'PSY', 64),
  ('HIP', 'MAMAMOO', 65),
  ('Dingga', 'MAMAMOO', 66),
  ('Egotistic', 'MAMAMOO', 67),
  ('Psycho', 'Red Velvet', 68),
  ('Red Flavor', 'Red Velvet', 69),
  ('Bad Boy', 'Red Velvet', 70),
  ('Queendom', 'Red Velvet', 71),
  ('Feel My Rhythm', 'Red Velvet', 72),
  ('Peek-A-Boo', 'Red Velvet', 73),
  ('ASAP', 'STAYC', 74),
  ('RUN2U', 'STAYC', 75),
  ('Stereotype', 'STAYC', 76),
  ('WANNABE', 'ITZY', 77),
  ('DALLA DALLA', 'ITZY', 78),
  ('Not Shy', 'ITZY', 79),
  ('LOCO', 'ITZY', 80),
  ('SNEAKERS', 'ITZY', 81),
  ('Cheshire', 'ITZY', 82),
  ('Born to Be', 'ITZY', 83),
  ('Bouncy', 'ATEEZ', 84),
  ('Wonderland', 'ATEEZ', 85),
  ('Say My Name', 'ATEEZ', 86),
  ('Guerrilla', 'ATEEZ', 87),
  ('Cherry Bomb', 'NCT 127', 88),
  ('Kick It', 'NCT 127', 89),
  ('Sticker', 'NCT 127', 90),
  ('Hot Sauce', 'NCT DREAM', 91),
  ('Ridin’', 'NCT DREAM', 92),
  ('Smoothie', 'NCT DREAM', 93),
  ('Gashina', 'SUNMI', 94),
  ('TAIL', 'SUNMI', 95),
  ('Cupid', 'FIFTY FIFTY', 96),
  ('Rollin’', 'Brave Girls', 97),
  ('Whiplash', 'aespa', 98),
  ('APT.', 'ROSÉ & Bruno Mars', 99)
) as v(title, artist, pos)
join public.songs s
  on lower(s.title) = lower(v.title) and lower(s.artist) = lower(v.artist)
join public.rounds r on r.label = 'Round 2 · 7:30 PM'
join public.events e on e.id = r.event_id and e.slug = 'vol-7';

insert into public.rounds (event_id, label, position)
select id, 'Finale · 8:30 PM', 2 from public.events where slug = 'vol-7';

insert into public.round_songs (round_id, song_id, position)
select r.id, s.id, v.pos
from (values
  ('Either Way'::text, 'IVE'::text, 0),
  ('Attention', 'NewJeans', 1),
  ('Hype Boy', 'NewJeans', 2),
  ('OMG', 'NewJeans', 3),
  ('ETA', 'NewJeans', 4),
  ('Cookie', 'NewJeans', 5),
  ('Bubble Gum', 'NewJeans', 6),
  ('ANTIFRAGILE', 'LE SSERAFIM', 7),
  ('FEARLESS', 'LE SSERAFIM', 8),
  ('Smart', 'LE SSERAFIM', 9),
  ('CRAZY', 'LE SSERAFIM', 10),
  ('TOMBOY', '(G)I-DLE', 11),
  ('Nxde', '(G)I-DLE', 12),
  ('LATATA', '(G)I-DLE', 13),
  ('Oh my god', '(G)I-DLE', 14),
  ('Super Lady', '(G)I-DLE', 15),
  ('Klaxon', '(G)I-DLE', 16),
  ('God’s Menu', 'Stray Kids', 17),
  ('Back Door', 'Stray Kids', 18),
  ('MANIAC', 'Stray Kids', 19),
  ('CASE 143', 'Stray Kids', 20),
  ('LALALALA', 'Stray Kids', 21),
  ('Thunderous', 'Stray Kids', 22),
  ('Growl', 'EXO', 23),
  ('Love Shot', 'EXO', 24),
  ('Monster', 'EXO', 25),
  ('Ko Ko Bop', 'EXO', 26),
  ('FANTASTIC BABY', 'BIGBANG', 27),
  ('BANG BANG BANG', 'BIGBANG', 28),
  ('Gangnam Style', 'PSY', 29),
  ('That That', 'PSY', 30),
  ('HIP', 'MAMAMOO', 31),
  ('Dingga', 'MAMAMOO', 32),
  ('Egotistic', 'MAMAMOO', 33),
  ('Psycho', 'Red Velvet', 34),
  ('Red Flavor', 'Red Velvet', 35),
  ('Bad Boy', 'Red Velvet', 36),
  ('Queendom', 'Red Velvet', 37),
  ('Feel My Rhythm', 'Red Velvet', 38),
  ('Peek-A-Boo', 'Red Velvet', 39)
) as v(title, artist, pos)
join public.songs s
  on lower(s.title) = lower(v.title) and lower(s.artist) = lower(v.artist)
join public.rounds r on r.label = 'Finale · 8:30 PM'
join public.events e on e.id = r.event_id and e.slug = 'vol-7';

-- RPD Vol. 6 — 2 rounds
delete from public.rounds r using public.events e
  where r.event_id = e.id and e.slug = 'vol-6';

insert into public.rounds (event_id, label, position)
select id, 'Round 1', 0 from public.events where slug = 'vol-6';

insert into public.round_songs (round_id, song_id, position)
select r.id, s.id, v.pos
from (values
  ('Supernova'::text, 'aespa'::text, 0),
  ('EASY', 'LE SSERAFIM', 1),
  ('Deja Vu', 'TXT', 2),
  ('Impossible', 'RIIZE', 3),
  ('SHEESH', 'BABYMONSTER', 4),
  ('Super Shy', 'NewJeans', 5),
  ('S-Class', 'Stray Kids', 6),
  ('I AM', 'IVE', 7),
  ('Queencard', '(G)I-DLE', 8),
  ('Spicy', 'aespa', 9),
  ('UNFORGIVEN', 'LE SSERAFIM', 10),
  ('Ditto', 'NewJeans', 11),
  ('Teddy Bear', 'STAYC', 12),
  ('Drama', 'aespa', 13),
  ('Perfect Night', 'LE SSERAFIM', 14),
  ('Standing Next to You', 'Jung Kook', 15),
  ('Get A Guitar', 'RIIZE', 16),
  ('You & Me', 'JENNIE', 17),
  ('Love Me Again', 'V', 18),
  ('HOT', 'LE SSERAFIM', 19),
  ('Kill This Love', 'BLACKPINK', 20),
  ('How You Like That', 'BLACKPINK', 21),
  ('DDU-DU DDU-DU', 'BLACKPINK', 22),
  ('Pink Venom', 'BLACKPINK', 23),
  ('Shut Down', 'BLACKPINK', 24),
  ('Lovesick Girls', 'BLACKPINK', 25),
  ('BOOMBAYAH', 'BLACKPINK', 26),
  ('As If It’s Your Last', 'BLACKPINK', 27),
  ('Dynamite', 'BTS', 28),
  ('Butter', 'BTS', 29),
  ('Boy With Luv', 'BTS', 30),
  ('IDOL', 'BTS', 31),
  ('FAKE LOVE', 'BTS', 32),
  ('DNA', 'BTS', 33),
  ('Blood Sweat & Tears', 'BTS', 34),
  ('MIC Drop', 'BTS', 35),
  ('Permission to Dance', 'BTS', 36),
  ('FANCY', 'TWICE', 37),
  ('TT', 'TWICE', 38),
  ('LIKEY', 'TWICE', 39),
  ('What is Love?', 'TWICE', 40),
  ('Feel Special', 'TWICE', 41),
  ('MORE & MORE', 'TWICE', 42),
  ('I CAN’T STOP ME', 'TWICE', 43),
  ('The Feels', 'TWICE', 44),
  ('SET ME FREE', 'TWICE', 45),
  ('Cheer Up', 'TWICE', 46),
  ('Next Level', 'aespa', 47),
  ('Savage', 'aespa', 48),
  ('Black Mamba', 'aespa', 49),
  ('Girls', 'aespa', 50),
  ('Dun Dun Dance', 'OH MY GIRL', 51),
  ('Nonstop', 'OH MY GIRL', 52),
  ('Secret Garden', 'OH MY GIRL', 53),
  ('LOVE DIVE', 'IVE', 54),
  ('After LIKE', 'IVE', 55),
  ('ELEVEN', 'IVE', 56),
  ('Kitsch', 'IVE', 57),
  ('Baddie', 'IVE', 58),
  ('Either Way', 'IVE', 59),
  ('Attention', 'NewJeans', 60),
  ('Hype Boy', 'NewJeans', 61),
  ('OMG', 'NewJeans', 62),
  ('ETA', 'NewJeans', 63),
  ('Cookie', 'NewJeans', 64),
  ('Bubble Gum', 'NewJeans', 65),
  ('ANTIFRAGILE', 'LE SSERAFIM', 66),
  ('FEARLESS', 'LE SSERAFIM', 67),
  ('Smart', 'LE SSERAFIM', 68),
  ('CRAZY', 'LE SSERAFIM', 69),
  ('TOMBOY', '(G)I-DLE', 70),
  ('Nxde', '(G)I-DLE', 71),
  ('LATATA', '(G)I-DLE', 72),
  ('Oh my god', '(G)I-DLE', 73),
  ('Super Lady', '(G)I-DLE', 74),
  ('Klaxon', '(G)I-DLE', 75),
  ('God’s Menu', 'Stray Kids', 76),
  ('Back Door', 'Stray Kids', 77),
  ('MANIAC', 'Stray Kids', 78),
  ('CASE 143', 'Stray Kids', 79),
  ('LALALALA', 'Stray Kids', 80),
  ('Thunderous', 'Stray Kids', 81),
  ('Growl', 'EXO', 82),
  ('Love Shot', 'EXO', 83),
  ('Monster', 'EXO', 84),
  ('Ko Ko Bop', 'EXO', 85),
  ('FANTASTIC BABY', 'BIGBANG', 86),
  ('BANG BANG BANG', 'BIGBANG', 87),
  ('Gangnam Style', 'PSY', 88),
  ('That That', 'PSY', 89),
  ('HIP', 'MAMAMOO', 90),
  ('Dingga', 'MAMAMOO', 91),
  ('Egotistic', 'MAMAMOO', 92),
  ('Psycho', 'Red Velvet', 93),
  ('Red Flavor', 'Red Velvet', 94),
  ('Bad Boy', 'Red Velvet', 95),
  ('Queendom', 'Red Velvet', 96),
  ('Feel My Rhythm', 'Red Velvet', 97),
  ('Peek-A-Boo', 'Red Velvet', 98),
  ('ASAP', 'STAYC', 99)
) as v(title, artist, pos)
join public.songs s
  on lower(s.title) = lower(v.title) and lower(s.artist) = lower(v.artist)
join public.rounds r on r.label = 'Round 1'
join public.events e on e.id = r.event_id and e.slug = 'vol-6';

insert into public.rounds (event_id, label, position)
select id, 'Round 2', 1 from public.events where slug = 'vol-6';

insert into public.round_songs (round_id, song_id, position)
select r.id, s.id, v.pos
from (values
  ('I CAN’T STOP ME'::text, 'TWICE'::text, 0),
  ('The Feels', 'TWICE', 1),
  ('SET ME FREE', 'TWICE', 2),
  ('Cheer Up', 'TWICE', 3),
  ('Next Level', 'aespa', 4),
  ('Savage', 'aespa', 5),
  ('Black Mamba', 'aespa', 6),
  ('Girls', 'aespa', 7),
  ('Dun Dun Dance', 'OH MY GIRL', 8),
  ('Nonstop', 'OH MY GIRL', 9),
  ('Secret Garden', 'OH MY GIRL', 10),
  ('LOVE DIVE', 'IVE', 11),
  ('After LIKE', 'IVE', 12),
  ('ELEVEN', 'IVE', 13),
  ('Kitsch', 'IVE', 14),
  ('Baddie', 'IVE', 15),
  ('Either Way', 'IVE', 16),
  ('Attention', 'NewJeans', 17),
  ('Hype Boy', 'NewJeans', 18),
  ('OMG', 'NewJeans', 19),
  ('ETA', 'NewJeans', 20),
  ('Cookie', 'NewJeans', 21),
  ('Bubble Gum', 'NewJeans', 22),
  ('ANTIFRAGILE', 'LE SSERAFIM', 23),
  ('FEARLESS', 'LE SSERAFIM', 24),
  ('Smart', 'LE SSERAFIM', 25),
  ('CRAZY', 'LE SSERAFIM', 26),
  ('TOMBOY', '(G)I-DLE', 27),
  ('Nxde', '(G)I-DLE', 28),
  ('LATATA', '(G)I-DLE', 29),
  ('Oh my god', '(G)I-DLE', 30),
  ('Super Lady', '(G)I-DLE', 31),
  ('Klaxon', '(G)I-DLE', 32),
  ('God’s Menu', 'Stray Kids', 33),
  ('Back Door', 'Stray Kids', 34),
  ('MANIAC', 'Stray Kids', 35),
  ('CASE 143', 'Stray Kids', 36),
  ('LALALALA', 'Stray Kids', 37),
  ('Thunderous', 'Stray Kids', 38),
  ('Growl', 'EXO', 39),
  ('Love Shot', 'EXO', 40),
  ('Monster', 'EXO', 41),
  ('Ko Ko Bop', 'EXO', 42),
  ('FANTASTIC BABY', 'BIGBANG', 43),
  ('BANG BANG BANG', 'BIGBANG', 44),
  ('Gangnam Style', 'PSY', 45),
  ('That That', 'PSY', 46),
  ('HIP', 'MAMAMOO', 47),
  ('Dingga', 'MAMAMOO', 48),
  ('Egotistic', 'MAMAMOO', 49),
  ('Psycho', 'Red Velvet', 50),
  ('Red Flavor', 'Red Velvet', 51),
  ('Bad Boy', 'Red Velvet', 52),
  ('Queendom', 'Red Velvet', 53),
  ('Feel My Rhythm', 'Red Velvet', 54),
  ('Peek-A-Boo', 'Red Velvet', 55),
  ('ASAP', 'STAYC', 56),
  ('RUN2U', 'STAYC', 57),
  ('Stereotype', 'STAYC', 58),
  ('WANNABE', 'ITZY', 59),
  ('DALLA DALLA', 'ITZY', 60),
  ('Not Shy', 'ITZY', 61),
  ('LOCO', 'ITZY', 62),
  ('SNEAKERS', 'ITZY', 63),
  ('Cheshire', 'ITZY', 64),
  ('Born to Be', 'ITZY', 65),
  ('Bouncy', 'ATEEZ', 66),
  ('Wonderland', 'ATEEZ', 67),
  ('Say My Name', 'ATEEZ', 68),
  ('Guerrilla', 'ATEEZ', 69),
  ('Cherry Bomb', 'NCT 127', 70),
  ('Kick It', 'NCT 127', 71),
  ('Sticker', 'NCT 127', 72),
  ('Hot Sauce', 'NCT DREAM', 73),
  ('Ridin’', 'NCT DREAM', 74),
  ('Smoothie', 'NCT DREAM', 75),
  ('Gashina', 'SUNMI', 76),
  ('TAIL', 'SUNMI', 77),
  ('Cupid', 'FIFTY FIFTY', 78),
  ('Rollin’', 'Brave Girls', 79),
  ('Whiplash', 'aespa', 80),
  ('APT.', 'ROSÉ & Bruno Mars', 81),
  ('How Sweet', 'NewJeans', 82),
  ('Magnetic', 'ILLIT', 83),
  ('Fate', '(G)I-DLE', 84),
  ('SPOT!', 'ZICO & JENNIE', 85),
  ('Sticky', 'KISS OF LIFE', 86),
  ('Chk Chk Boom', 'Stray Kids', 87),
  ('Armageddon', 'aespa', 88),
  ('Igloo', 'KISS OF LIFE', 89)
) as v(title, artist, pos)
join public.songs s
  on lower(s.title) = lower(v.title) and lower(s.artist) = lower(v.artist)
join public.rounds r on r.label = 'Round 2'
join public.events e on e.id = r.event_id and e.slug = 'vol-6';

-- RPD Vol. 5 — 2 rounds
delete from public.rounds r using public.events e
  where r.event_id = e.id and e.slug = 'vol-5';

insert into public.rounds (event_id, label, position)
select id, 'Round 1', 0 from public.events where slug = 'vol-5';

insert into public.round_songs (round_id, song_id, position)
select r.id, s.id, v.pos
from (values
  ('Teddy Bear'::text, 'STAYC'::text, 0),
  ('Drama', 'aespa', 1),
  ('Perfect Night', 'LE SSERAFIM', 2),
  ('Standing Next to You', 'Jung Kook', 3),
  ('Get A Guitar', 'RIIZE', 4),
  ('You & Me', 'JENNIE', 5),
  ('Love Me Again', 'V', 6),
  ('HOT', 'LE SSERAFIM', 7),
  ('Kill This Love', 'BLACKPINK', 8),
  ('How You Like That', 'BLACKPINK', 9),
  ('DDU-DU DDU-DU', 'BLACKPINK', 10),
  ('Pink Venom', 'BLACKPINK', 11),
  ('Shut Down', 'BLACKPINK', 12),
  ('Lovesick Girls', 'BLACKPINK', 13),
  ('BOOMBAYAH', 'BLACKPINK', 14),
  ('As If It’s Your Last', 'BLACKPINK', 15),
  ('Dynamite', 'BTS', 16),
  ('Butter', 'BTS', 17),
  ('Boy With Luv', 'BTS', 18),
  ('IDOL', 'BTS', 19),
  ('FAKE LOVE', 'BTS', 20),
  ('DNA', 'BTS', 21),
  ('Blood Sweat & Tears', 'BTS', 22),
  ('MIC Drop', 'BTS', 23),
  ('Permission to Dance', 'BTS', 24),
  ('FANCY', 'TWICE', 25),
  ('TT', 'TWICE', 26),
  ('LIKEY', 'TWICE', 27),
  ('What is Love?', 'TWICE', 28),
  ('Feel Special', 'TWICE', 29),
  ('MORE & MORE', 'TWICE', 30),
  ('I CAN’T STOP ME', 'TWICE', 31),
  ('The Feels', 'TWICE', 32),
  ('SET ME FREE', 'TWICE', 33),
  ('Cheer Up', 'TWICE', 34),
  ('Next Level', 'aespa', 35),
  ('Savage', 'aespa', 36),
  ('Black Mamba', 'aespa', 37),
  ('Girls', 'aespa', 38),
  ('Dun Dun Dance', 'OH MY GIRL', 39),
  ('Nonstop', 'OH MY GIRL', 40),
  ('Secret Garden', 'OH MY GIRL', 41),
  ('LOVE DIVE', 'IVE', 42),
  ('After LIKE', 'IVE', 43),
  ('ELEVEN', 'IVE', 44),
  ('Kitsch', 'IVE', 45),
  ('Baddie', 'IVE', 46),
  ('Either Way', 'IVE', 47),
  ('Attention', 'NewJeans', 48),
  ('Hype Boy', 'NewJeans', 49),
  ('OMG', 'NewJeans', 50),
  ('ETA', 'NewJeans', 51),
  ('Cookie', 'NewJeans', 52),
  ('Bubble Gum', 'NewJeans', 53),
  ('ANTIFRAGILE', 'LE SSERAFIM', 54),
  ('FEARLESS', 'LE SSERAFIM', 55),
  ('Smart', 'LE SSERAFIM', 56),
  ('CRAZY', 'LE SSERAFIM', 57),
  ('TOMBOY', '(G)I-DLE', 58),
  ('Nxde', '(G)I-DLE', 59),
  ('LATATA', '(G)I-DLE', 60),
  ('Oh my god', '(G)I-DLE', 61),
  ('Super Lady', '(G)I-DLE', 62),
  ('Klaxon', '(G)I-DLE', 63),
  ('God’s Menu', 'Stray Kids', 64),
  ('Back Door', 'Stray Kids', 65),
  ('MANIAC', 'Stray Kids', 66),
  ('CASE 143', 'Stray Kids', 67),
  ('LALALALA', 'Stray Kids', 68),
  ('Thunderous', 'Stray Kids', 69),
  ('Growl', 'EXO', 70),
  ('Love Shot', 'EXO', 71),
  ('Monster', 'EXO', 72),
  ('Ko Ko Bop', 'EXO', 73),
  ('FANTASTIC BABY', 'BIGBANG', 74),
  ('BANG BANG BANG', 'BIGBANG', 75),
  ('Gangnam Style', 'PSY', 76),
  ('That That', 'PSY', 77),
  ('HIP', 'MAMAMOO', 78),
  ('Dingga', 'MAMAMOO', 79),
  ('Egotistic', 'MAMAMOO', 80),
  ('Psycho', 'Red Velvet', 81),
  ('Red Flavor', 'Red Velvet', 82),
  ('Bad Boy', 'Red Velvet', 83),
  ('Queendom', 'Red Velvet', 84),
  ('Feel My Rhythm', 'Red Velvet', 85),
  ('Peek-A-Boo', 'Red Velvet', 86),
  ('ASAP', 'STAYC', 87),
  ('RUN2U', 'STAYC', 88),
  ('Stereotype', 'STAYC', 89),
  ('WANNABE', 'ITZY', 90),
  ('DALLA DALLA', 'ITZY', 91),
  ('Not Shy', 'ITZY', 92),
  ('LOCO', 'ITZY', 93),
  ('SNEAKERS', 'ITZY', 94),
  ('Cheshire', 'ITZY', 95),
  ('Born to Be', 'ITZY', 96),
  ('Bouncy', 'ATEEZ', 97),
  ('Wonderland', 'ATEEZ', 98),
  ('Say My Name', 'ATEEZ', 99)
) as v(title, artist, pos)
join public.songs s
  on lower(s.title) = lower(v.title) and lower(s.artist) = lower(v.artist)
join public.rounds r on r.label = 'Round 1'
join public.events e on e.id = r.event_id and e.slug = 'vol-5';

insert into public.rounds (event_id, label, position)
select id, 'Round 2', 1 from public.events where slug = 'vol-5';

insert into public.round_songs (round_id, song_id, position)
select r.id, s.id, v.pos
from (values
  ('Nxde'::text, '(G)I-DLE'::text, 0),
  ('LATATA', '(G)I-DLE', 1),
  ('Oh my god', '(G)I-DLE', 2),
  ('Super Lady', '(G)I-DLE', 3),
  ('Klaxon', '(G)I-DLE', 4),
  ('God’s Menu', 'Stray Kids', 5),
  ('Back Door', 'Stray Kids', 6),
  ('MANIAC', 'Stray Kids', 7),
  ('CASE 143', 'Stray Kids', 8),
  ('LALALALA', 'Stray Kids', 9),
  ('Thunderous', 'Stray Kids', 10),
  ('Growl', 'EXO', 11),
  ('Love Shot', 'EXO', 12),
  ('Monster', 'EXO', 13),
  ('Ko Ko Bop', 'EXO', 14),
  ('FANTASTIC BABY', 'BIGBANG', 15),
  ('BANG BANG BANG', 'BIGBANG', 16),
  ('Gangnam Style', 'PSY', 17),
  ('That That', 'PSY', 18),
  ('HIP', 'MAMAMOO', 19),
  ('Dingga', 'MAMAMOO', 20),
  ('Egotistic', 'MAMAMOO', 21),
  ('Psycho', 'Red Velvet', 22),
  ('Red Flavor', 'Red Velvet', 23),
  ('Bad Boy', 'Red Velvet', 24),
  ('Queendom', 'Red Velvet', 25),
  ('Feel My Rhythm', 'Red Velvet', 26),
  ('Peek-A-Boo', 'Red Velvet', 27),
  ('ASAP', 'STAYC', 28),
  ('RUN2U', 'STAYC', 29),
  ('Stereotype', 'STAYC', 30),
  ('WANNABE', 'ITZY', 31),
  ('DALLA DALLA', 'ITZY', 32),
  ('Not Shy', 'ITZY', 33),
  ('LOCO', 'ITZY', 34),
  ('SNEAKERS', 'ITZY', 35),
  ('Cheshire', 'ITZY', 36),
  ('Born to Be', 'ITZY', 37),
  ('Bouncy', 'ATEEZ', 38),
  ('Wonderland', 'ATEEZ', 39),
  ('Say My Name', 'ATEEZ', 40),
  ('Guerrilla', 'ATEEZ', 41),
  ('Cherry Bomb', 'NCT 127', 42),
  ('Kick It', 'NCT 127', 43),
  ('Sticker', 'NCT 127', 44),
  ('Hot Sauce', 'NCT DREAM', 45),
  ('Ridin’', 'NCT DREAM', 46),
  ('Smoothie', 'NCT DREAM', 47),
  ('Gashina', 'SUNMI', 48),
  ('TAIL', 'SUNMI', 49),
  ('Cupid', 'FIFTY FIFTY', 50),
  ('Rollin’', 'Brave Girls', 51),
  ('Whiplash', 'aespa', 52),
  ('APT.', 'ROSÉ & Bruno Mars', 53),
  ('How Sweet', 'NewJeans', 54),
  ('Magnetic', 'ILLIT', 55),
  ('Fate', '(G)I-DLE', 56),
  ('SPOT!', 'ZICO & JENNIE', 57),
  ('Sticky', 'KISS OF LIFE', 58),
  ('Chk Chk Boom', 'Stray Kids', 59),
  ('Armageddon', 'aespa', 60),
  ('Igloo', 'KISS OF LIFE', 61),
  ('Mantra', 'JENNIE', 62),
  ('POWER', 'G-Dragon', 63),
  ('Supernova', 'aespa', 64),
  ('EASY', 'LE SSERAFIM', 65),
  ('Deja Vu', 'TXT', 66),
  ('Impossible', 'RIIZE', 67),
  ('SHEESH', 'BABYMONSTER', 68),
  ('Super Shy', 'NewJeans', 69),
  ('S-Class', 'Stray Kids', 70),
  ('I AM', 'IVE', 71),
  ('Queencard', '(G)I-DLE', 72),
  ('Spicy', 'aespa', 73),
  ('UNFORGIVEN', 'LE SSERAFIM', 74),
  ('Ditto', 'NewJeans', 75),
  ('Teddy Bear', 'STAYC', 76),
  ('Drama', 'aespa', 77),
  ('Perfect Night', 'LE SSERAFIM', 78),
  ('Standing Next to You', 'Jung Kook', 79),
  ('Get A Guitar', 'RIIZE', 80),
  ('You & Me', 'JENNIE', 81),
  ('Love Me Again', 'V', 82),
  ('HOT', 'LE SSERAFIM', 83),
  ('Kill This Love', 'BLACKPINK', 84),
  ('How You Like That', 'BLACKPINK', 85),
  ('DDU-DU DDU-DU', 'BLACKPINK', 86),
  ('Pink Venom', 'BLACKPINK', 87),
  ('Shut Down', 'BLACKPINK', 88),
  ('Lovesick Girls', 'BLACKPINK', 89),
  ('BOOMBAYAH', 'BLACKPINK', 90),
  ('As If It’s Your Last', 'BLACKPINK', 91),
  ('Dynamite', 'BTS', 92),
  ('Butter', 'BTS', 93),
  ('Boy With Luv', 'BTS', 94),
  ('IDOL', 'BTS', 95),
  ('FAKE LOVE', 'BTS', 96),
  ('DNA', 'BTS', 97),
  ('Blood Sweat & Tears', 'BTS', 98),
  ('MIC Drop', 'BTS', 99)
) as v(title, artist, pos)
join public.songs s
  on lower(s.title) = lower(v.title) and lower(s.artist) = lower(v.artist)
join public.rounds r on r.label = 'Round 2'
join public.events e on e.id = r.event_id and e.slug = 'vol-5';

-- RPD Vol. 4 — 2 rounds
delete from public.rounds r using public.events e
  where r.event_id = e.id and e.slug = 'vol-4';

insert into public.rounds (event_id, label, position)
select id, 'Round 1', 0 from public.events where slug = 'vol-4';

insert into public.round_songs (round_id, song_id, position)
select r.id, s.id, v.pos
from (values
  ('Magnetic'::text, 'ILLIT'::text, 0),
  ('Fate', '(G)I-DLE', 1),
  ('SPOT!', 'ZICO & JENNIE', 2),
  ('Sticky', 'KISS OF LIFE', 3),
  ('Chk Chk Boom', 'Stray Kids', 4),
  ('Armageddon', 'aespa', 5),
  ('Igloo', 'KISS OF LIFE', 6),
  ('Mantra', 'JENNIE', 7),
  ('POWER', 'G-Dragon', 8),
  ('Supernova', 'aespa', 9),
  ('EASY', 'LE SSERAFIM', 10),
  ('Deja Vu', 'TXT', 11),
  ('Impossible', 'RIIZE', 12),
  ('SHEESH', 'BABYMONSTER', 13),
  ('Super Shy', 'NewJeans', 14),
  ('S-Class', 'Stray Kids', 15),
  ('I AM', 'IVE', 16),
  ('Queencard', '(G)I-DLE', 17),
  ('Spicy', 'aespa', 18),
  ('UNFORGIVEN', 'LE SSERAFIM', 19),
  ('Ditto', 'NewJeans', 20),
  ('Teddy Bear', 'STAYC', 21),
  ('Drama', 'aespa', 22),
  ('Perfect Night', 'LE SSERAFIM', 23),
  ('Standing Next to You', 'Jung Kook', 24),
  ('Get A Guitar', 'RIIZE', 25),
  ('You & Me', 'JENNIE', 26),
  ('Love Me Again', 'V', 27),
  ('HOT', 'LE SSERAFIM', 28),
  ('Kill This Love', 'BLACKPINK', 29),
  ('How You Like That', 'BLACKPINK', 30),
  ('DDU-DU DDU-DU', 'BLACKPINK', 31),
  ('Pink Venom', 'BLACKPINK', 32),
  ('Shut Down', 'BLACKPINK', 33),
  ('Lovesick Girls', 'BLACKPINK', 34),
  ('BOOMBAYAH', 'BLACKPINK', 35),
  ('As If It’s Your Last', 'BLACKPINK', 36),
  ('Dynamite', 'BTS', 37),
  ('Butter', 'BTS', 38),
  ('Boy With Luv', 'BTS', 39),
  ('IDOL', 'BTS', 40),
  ('FAKE LOVE', 'BTS', 41),
  ('DNA', 'BTS', 42),
  ('Blood Sweat & Tears', 'BTS', 43),
  ('MIC Drop', 'BTS', 44),
  ('Permission to Dance', 'BTS', 45),
  ('FANCY', 'TWICE', 46),
  ('TT', 'TWICE', 47),
  ('LIKEY', 'TWICE', 48),
  ('What is Love?', 'TWICE', 49),
  ('Feel Special', 'TWICE', 50),
  ('MORE & MORE', 'TWICE', 51),
  ('I CAN’T STOP ME', 'TWICE', 52),
  ('The Feels', 'TWICE', 53),
  ('SET ME FREE', 'TWICE', 54),
  ('Cheer Up', 'TWICE', 55),
  ('Next Level', 'aespa', 56),
  ('Savage', 'aespa', 57),
  ('Black Mamba', 'aespa', 58),
  ('Girls', 'aespa', 59),
  ('Dun Dun Dance', 'OH MY GIRL', 60),
  ('Nonstop', 'OH MY GIRL', 61),
  ('Secret Garden', 'OH MY GIRL', 62),
  ('LOVE DIVE', 'IVE', 63),
  ('After LIKE', 'IVE', 64),
  ('ELEVEN', 'IVE', 65),
  ('Kitsch', 'IVE', 66),
  ('Baddie', 'IVE', 67),
  ('Either Way', 'IVE', 68),
  ('Attention', 'NewJeans', 69),
  ('Hype Boy', 'NewJeans', 70),
  ('OMG', 'NewJeans', 71),
  ('ETA', 'NewJeans', 72),
  ('Cookie', 'NewJeans', 73),
  ('Bubble Gum', 'NewJeans', 74),
  ('ANTIFRAGILE', 'LE SSERAFIM', 75),
  ('FEARLESS', 'LE SSERAFIM', 76),
  ('Smart', 'LE SSERAFIM', 77),
  ('CRAZY', 'LE SSERAFIM', 78),
  ('TOMBOY', '(G)I-DLE', 79)
) as v(title, artist, pos)
join public.songs s
  on lower(s.title) = lower(v.title) and lower(s.artist) = lower(v.artist)
join public.rounds r on r.label = 'Round 1'
join public.events e on e.id = r.event_id and e.slug = 'vol-4';

insert into public.rounds (event_id, label, position)
select id, 'Round 2', 1 from public.events where slug = 'vol-4';

insert into public.round_songs (round_id, song_id, position)
select r.id, s.id, v.pos
from (values
  ('MIC Drop'::text, 'BTS'::text, 0),
  ('Permission to Dance', 'BTS', 1),
  ('FANCY', 'TWICE', 2),
  ('TT', 'TWICE', 3),
  ('LIKEY', 'TWICE', 4),
  ('What is Love?', 'TWICE', 5),
  ('Feel Special', 'TWICE', 6),
  ('MORE & MORE', 'TWICE', 7),
  ('I CAN’T STOP ME', 'TWICE', 8),
  ('The Feels', 'TWICE', 9),
  ('SET ME FREE', 'TWICE', 10),
  ('Cheer Up', 'TWICE', 11),
  ('Next Level', 'aespa', 12),
  ('Savage', 'aespa', 13),
  ('Black Mamba', 'aespa', 14),
  ('Girls', 'aespa', 15),
  ('Dun Dun Dance', 'OH MY GIRL', 16),
  ('Nonstop', 'OH MY GIRL', 17),
  ('Secret Garden', 'OH MY GIRL', 18),
  ('LOVE DIVE', 'IVE', 19),
  ('After LIKE', 'IVE', 20),
  ('ELEVEN', 'IVE', 21),
  ('Kitsch', 'IVE', 22),
  ('Baddie', 'IVE', 23),
  ('Either Way', 'IVE', 24),
  ('Attention', 'NewJeans', 25),
  ('Hype Boy', 'NewJeans', 26),
  ('OMG', 'NewJeans', 27),
  ('ETA', 'NewJeans', 28),
  ('Cookie', 'NewJeans', 29),
  ('Bubble Gum', 'NewJeans', 30),
  ('ANTIFRAGILE', 'LE SSERAFIM', 31),
  ('FEARLESS', 'LE SSERAFIM', 32),
  ('Smart', 'LE SSERAFIM', 33),
  ('CRAZY', 'LE SSERAFIM', 34),
  ('TOMBOY', '(G)I-DLE', 35),
  ('Nxde', '(G)I-DLE', 36),
  ('LATATA', '(G)I-DLE', 37),
  ('Oh my god', '(G)I-DLE', 38),
  ('Super Lady', '(G)I-DLE', 39),
  ('Klaxon', '(G)I-DLE', 40),
  ('God’s Menu', 'Stray Kids', 41),
  ('Back Door', 'Stray Kids', 42),
  ('MANIAC', 'Stray Kids', 43),
  ('CASE 143', 'Stray Kids', 44),
  ('LALALALA', 'Stray Kids', 45),
  ('Thunderous', 'Stray Kids', 46),
  ('Growl', 'EXO', 47),
  ('Love Shot', 'EXO', 48),
  ('Monster', 'EXO', 49),
  ('Ko Ko Bop', 'EXO', 50),
  ('FANTASTIC BABY', 'BIGBANG', 51),
  ('BANG BANG BANG', 'BIGBANG', 52),
  ('Gangnam Style', 'PSY', 53),
  ('That That', 'PSY', 54),
  ('HIP', 'MAMAMOO', 55),
  ('Dingga', 'MAMAMOO', 56),
  ('Egotistic', 'MAMAMOO', 57),
  ('Psycho', 'Red Velvet', 58),
  ('Red Flavor', 'Red Velvet', 59),
  ('Bad Boy', 'Red Velvet', 60),
  ('Queendom', 'Red Velvet', 61),
  ('Feel My Rhythm', 'Red Velvet', 62),
  ('Peek-A-Boo', 'Red Velvet', 63),
  ('ASAP', 'STAYC', 64),
  ('RUN2U', 'STAYC', 65),
  ('Stereotype', 'STAYC', 66),
  ('WANNABE', 'ITZY', 67),
  ('DALLA DALLA', 'ITZY', 68),
  ('Not Shy', 'ITZY', 69)
) as v(title, artist, pos)
join public.songs s
  on lower(s.title) = lower(v.title) and lower(s.artist) = lower(v.artist)
join public.rounds r on r.label = 'Round 2'
join public.events e on e.id = r.event_id and e.slug = 'vol-4';

delete from public.faqs;
insert into public.faqs (question, answer, position) values
  ('What is a random play dance (RPD)?', 'A playlist of K-pop songs plays in short segments in random order. When a song you know comes on, run to the center and dance the choreography. When it ends, run back. Chaos, in the best way.', 0),
  ('Do I need to know the full choreography?', 'Nope! Most people only know the chorus — that is totally fine. Dance what you know, vibe for the rest.', 1),
  ('Is it free? Do I need to register?', 'Always free, no registration. Just show up. Follow @daqtad on Instagram so you know when and where.', 2),
  ('How do song requests work?', 'Before each event we open requests on the event page. The most-requested songs make the playlist. One request per song, but you can request as many songs as you like.', 3),
  ('Can I get the photos from an event?', 'Yes! Every event page has an album link, and everything lives in our shared Google Drive — free to download and post (tag us 💜).', 4);

update public.site_settings set
  instagram = 'https://instagram.com/daqtad',
  facebook = 'https://fb.com/daqtad',
  drive = 'https://drive.google.com/drive/folders/1ESfNKgpqy1SydvTTofl5t4PIRBkzRZVd'
where id = true;

